# Generated by Django 5.2.6 on 2025-09-22 20:59

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_must_change_pw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('license', 'Лицензия'), ('permit', 'Разрешение'), ('policy', 'Полис'), ('cert', 'Сертификат'), ('other', 'Другое')], default='other', max_length=32)),
                ('version', models.PositiveIntegerField(default=1)),
                ('file', models.FileField(blank=True, null=True, upload_to=accounts.models.doc_upload_to)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
