# Generated by Django 5.2.6 on 2025-09-22 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='version',
        ),
    ]
