# Generated by Django 5.2.6 on 2025-11-08 13:02

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_document_file_documentfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentfile',
            name='document',
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-updated_at', 'id']},
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.doc_upload_to),
        ),
        migrations.AlterField(
            model_name='document',
            name='expires_at',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='kind',
            field=models.CharField(choices=[('license', 'Лицензия'), ('permit', 'Разрешение'), ('policy', 'Полис'), ('cert', 'Сертификат'), ('other', 'Другое')], db_index=True, default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner', 'is_active'], name='doc_owner_active_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner', '-updated_at'], name='doc_owner_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['kind'], name='doc_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['expires_at'], name='doc_expires_idx'),
        ),
        migrations.DeleteModel(
            name='DocumentFile',
        ),
    ]
