# Generated by Django 5.2.6 on 2025-11-08 13:58

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_documentfile_document_alter_document_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=accounts.models.doc_upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='accounts_do_owner_i_545343_idx',
            old_name='doc_owner_active_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='accounts_do_owner_i_2b623c_idx',
            old_name='doc_owner_updated_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='accounts_do_kind_e32f12_idx',
            old_name='doc_kind_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='accounts_do_expires_dcf6dc_idx',
            old_name='doc_expires_idx',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.AddField(
            model_name='documentfile',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='accounts.document'),
        ),
    ]
