# Generated by Django 5.2.6 on 2025-11-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_documentfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='kind',
            field=models.CharField(choices=[('personal', 'Личные'), ('business', 'Разрешения/лицензии'), ('dozvol', 'Дозвол')], db_index=True, default='personal', max_length=32),
        ),
    ]
