# Generated by Django 5.2.6 on 2025-11-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_invitetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitetoken',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
