# Generated by Django 5.2.6 on 2026-09-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='kind',
            field=models.CharField(choices=[('personal', 'Личные'), ('business', 'Путевка'), ('dozvol', 'Дозвол')], db_index=True, default='personal', max_length=32),
        ),
    ]
