# Generated by Django 5.2.6 on 2025-09-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=64)),
                ('version', models.IntegerField(default=1)),
                ('expires_at', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
