# Generated by Django 5.2.6 on 2025-09-09 07:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_file_document_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='recipients',
            field=models.ManyToManyField(blank=True, help_text='Пользователи, у которых документ будет в приложении', related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
